version: '3.3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - '32400:32400/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=claim-vD3xwKgsyFR1qNpusHXt #optional
      - TZ=America/Montevideo
    networks:
      - hello-net

  webserver:
    container_name: nginx
    image: nginx:alpine
    environment:
      TZ: America/Montevideo
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/nginx.conf
      - ./log:/var/log/nginx
      - certbot-acme:/var/www/letsencrypt/:ro
      - certbot-certs:/etc/letsencrypt/:ro
      - ./dhparam:/etc/ssl/certs
    networks:
      - hello-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-acme:/var/www/letsencrypt/:rw
      - certbot-certs:/etc/letsencrypt/:rw
    depends_on:
      - webserver
    command: certonly --webroot --force-renewal --agree-tos --no-eff-email --email mlaino@gmail.com -w /var/www/letsencrypt -d etniapagana.com -d www.etniapagana.com
    networks:
      - hello-net

volumes:
  certbot-acme:
  certbot-certs:

networks:
  hello-net:
    driver: bridge
