version: '3.3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - '32400:32400/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=claim-WBNK9rHLTT5fqgfZxbmX #optional
      - TZ=America/Montevideo
    networks:
      - hello-net

  nginx:
    container_name: nginx
    image: nginx:alpine
    environment:
      TZ: America/Montevideo
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks:
      - hello-net

networks:
  hello-net:
    driver: bridge
